apiVersion: v1
kind: ConfigMap
metadata:
  name: stackdriver-webhook-bridge
data:
  swb-config.yaml: |
    # Forward converted k8s audit events to this url.
    url: http://sysdig-agent.sysdig-agent.svc.cluster.local:7765/k8s_audit

    # Read stackdriver logs from this project id. If blank, the bridge
    # will use the metadata service to find the project id.
    project:

    # Read stackdriver logs for this k8s cluster. If blank, the bridge
    # will use the metadata service to find the cluster name.
    cluster:

    # If provided, also write all log entries to this file. (Mostly
    # used for low-level debugging of conversion. Shouldn't be needed
    # in normal operation)
    logfile:

    # If provided, write all converted k8s audit events to this
    # file. (Mostly used for low-level debugging, not needed for
    # normal operation).
    outfile:

    # Poll interval for new stackdriver log messages.
    poll_interval: 5s

    # When reading stackdriver log messages, read this many seconds
    # behind "now" when reading. A small lag allows for the time it
    # takes for log messages to be sent by the api server and
    # available in stackdriver.
    lag_interval: 30s

    # Log Level
    log_level: info
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stackdriver-webhook-bridge
  labels:
    app: stackdriver-webhook-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stackdriver-webhook-bridge
  template:
    metadata:
      labels:
        app: stackdriver-webhook-bridge
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: stackdriver-webhook-bridge
        - name: swb-config
          configMap:
            name: stackdriver-webhook-bridge
            optional: true
      containers:
        - name: stackdriver-webhook-bridge
          image: sysdiglabs/stackdriver-webhook-bridge
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
            - name: swb-config
              mountPath: "/opt/swb/config"
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json